# Project data directories configurations

# Data Source configurations
Data_Source:
    src: hf
    src_repo: cfilt/iitb-english-hindi
    split: ["train", "validation", "test"]
    feature: translation
    cols_key: ["en", "hi"]

# Data Loader configurations
Data_Loader:
    root_dir: Data_Loader
    ign_root_dir: data
    

# Tokenizer configurations
Tokenizer:
    root_dir: Tokenizer
    src_data_dir: data
    temp_data_dir: temp_data
    sub_folders: ["en", "hi"]
    ckpts_bkt: Tokenizer_Ckpts
    

# Word Embedding configurations
Embedding:
    root_dir: Embedding
    src_data_dir: data
    ckpts_bkt: Embedding_Ckpts
    sub_folders: ["en", "hi"]

# Transformer configurations
Transformer:
